### ISSUE TITLE
hw06- TA comment

### ISSUE THREAD

**Issue by sherrie9** [STAT545-UBC-students/hw06-j-schaub#3]
- Overall, good job on both tasks. They showed good understanding of class materials
- For task 1, your output is in a strange format, it is embedded in html chunk? I am not sure what is going on there, perhaps changing to html file could be better.
- Good use of tables for counting vowels proportions, but too many decimal places.
- Task 2, good job in breaking down the problem and clean the data step by step. 
- could show random 10 rows of data in your table instead of first 10 rows, which does not capture what the data frame really looks like because all rows in candy column look the same. 
- could do some downstream analysis with the tidy data and generate some plots according to the instruction.

**Comment by j-schaub** [comment]
@sherrie9  @STAT545-UBC-students/2018_teaching_team 

I lost marks on this assignment because I did not display plots for task 2 (Candy data), but the instructions from the homework say to "work on *something* from this homework in 2015". I stated in my markdown file that I would tackle the data cleaning, and I was not under the impression that building plots was a requirement of this task.

Can anyone advise either way on this?

**Comment by sherrie9** [comment]
Hi Jessica,
        The instruction on the candy task states that you are required to do data wrangling and exploration. You only had the first part and no exploration. Exploration involves plotting. Please see "your mission" section of the instruction.

**Comment by j-schaub** [comment]
Hi @sherrie9!

Thanks for the quick reply! I understand that the homework from 2015 required the full wrangling, but the instructions from our homework said to "work on **something** from the 2015 homework". I assumed we did not have to complete the entire assignment, but only a portion of it because it was only 1/2 of our homework.

@vincenzocoia Any thoughts?

**Comment by vincenzocoia** [comment]
I think both points of view have merit. Since the assignment wasn't particularly clear, I'd rather not give out any penalty for this, so I'll ask @sherrie9 to reconsider the grade with this in mind. I'll make a note for next year. Thanks for keeping me in the loop.

**Comment by j-schaub** [comment]
@sherrie9 @vincenzocoia Thank you for weighing in, sorry to both the confusion!
